---
- name:
  hosts: all
  become: True
  tasks: 
    - name: copy a file to managed and set attributes
      copy:
        src: /tmp/test1.txt
        dest: /tmp/
        owner: user1
        group: user1
        mode: 0755
    - name: copy
      copy:
        content: " This is a file"
        dest: /tmp/test1.txt
